package com.app.instagramlikeimagevideopicker

enum class MediaTypeEnum { IMAGE_GALLERY_AND_CAPTURE, VIDEO_GALLERY_AND_CAPTURE, IMAGE_VIDEO_GALLERY_AND_CAPTURE, IMAGE_CAPTURE, VIDEO_CAPTURE, IMAGE_VIDEO_CAPTURE, IMAGE_VIDEO_GALLERY, IMAGE_GALLERY,
    VIDEO_GALLERY }